name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version that matches your development environment

      - name: Install dependencies
        run: npm ci
        working-directory: todolist  # Set the working directory for this step

      - name: Build the project
        run: npm run build
        working-directory: todolist  # Set the working directory for this step

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TODAY_AND_TOMORROW_C40EF }}
          channelId: live
          projectId: today-and-tomorrow-c40ef
